"use client"

import { useEffect, useReducer, useRef, useState } from "react"
import Link from "next/link"
import { futureCatalogue, futuresRoutes, scenarioHref } from "@/lib/futures/catalogue/index"
import { featureDefinitions, type FeatureId } from "@/lib/futures/catalogue/features"
import { preferenceQuestions, requirementLabels, nonPreferenceOptions, preferenceLabel, hasDirection, preferencesComplete, expectationFrame, type PreferenceAnswers, type Expectation } from "@/lib/futures/preferences"
import { initialPreferenceState, preferenceReducer } from "@/lib/futures/preference-state"
import { matchFutures, matchingMethod, descriptorEquivalenceGroups, equivalenceExplanation, type ScenarioComparison } from "@/lib/futures/matching"
import { interpretPreferences, comparisonParagraph, conditionQualification, desiredCondition, joinConditions } from "@/lib/futures/interpretation"
import { ComparisonExplorer } from "./comparison-explorer"
import styles from "./catalogue.module.css"

const expectationLabels = { plausible: "Plausible", unlikely: "Unlikely", unsure: "Unsure / insufficient basis" } as const
function Reasons({ comparison, answers }: { comparison: ScenarioComparison; answers: PreferenceAnswers }) {
  const groups: [string, FeatureId[]][] = [
    ["Conditions supported", comparison.supported], ["Conflicts with your priorities", comparison.conflicts.filter(id => !comparison.hardConflicts.includes(id))],
    ["Conflicts with confirmed non-negotiables", comparison.hardConflicts], ["Non-negotiables still unconfirmed", comparison.unconfirmedConstraints],
    ["Institutions or choices not instantiated here", comparison.inapplicable.filter(id => !comparison.unconfirmedConstraints.includes(id))],
    ["Other unresolved conditions", comparison.unresolved.filter(id => !comparison.unconfirmedConstraints.includes(id))],
  ]
  return <dl className={styles.reasons}>{groups.filter(([, ids]) => ids.length).map(([label, ids]) => <div key={label}><dt>{label}</dt><dd><ul>{ids.map(id => <li key={id}>{preferenceLabel(id, answers[id])}.<span className={styles.reasonExplanation}>{conditionQualification(comparison, id)}</span></li>)}</ul></dd></div>)}</dl>
}
function ShortlistEntry({ comparison, answers }: { comparison: ScenarioComparison; answers: PreferenceAnswers }) {
  return <article className={styles.resultEntry} data-scenario={comparison.scenario.id}>
    <div><h2>{comparison.scenario.name}</h2><Link href={scenarioHref(comparison.scenario.id)} target="_blank" rel="noopener" prefetch={false}>Read the full scenario and sources (new tab)</Link></div>
    <div><p>{comparisonParagraph(comparison, answers)}</p>
      {comparison.unconfirmedConstraints.length > 0 && <p className={styles.requirementNote}><strong>Indispensable but unconfirmed:</strong> {joinConditions(comparison.unconfirmedConstraints.map(id => desiredCondition(id, answers)))}. This entry remains provisional on those terms.</p>}
      <details className={styles.disclosure}><summary>Agreements, conflicts and unresolved terms</summary><Reasons comparison={comparison} answers={answers} /></details>
    </div>
  </article>
}
function Shortlist({ comparisons, answers }: { comparisons: ScenarioComparison[]; answers: PreferenceAnswers }) {
  const groups: ScenarioComparison[][] = []
  for (const comparison of comparisons) {
    const group = groups.find(group => Math.abs(group[0].orderingValue - comparison.orderingValue) < 1e-9)
    if (group) group.push(comparison); else groups.push([comparison])
  }
  return <div data-testid="shortlist">{groups.map(group => {
    const entries = group.map(comparison => <ShortlistEntry key={comparison.scenario.id} comparison={comparison} answers={answers} />)
    const common = group[0].supported.filter(id => group.every(c => c.supported.includes(id)))
    const tieText = group.length > 1 ? `Equal support across ${group.length} entries. ${common.length ? `They all support ${joinConditions(common.map(id => desiredCondition(id, answers)))}.` : "Different agreements and conflicts balance to the same ordering value."} Every tied entry is retained; the first name is not a winner.` : null
    return <div key={group[0].scenario.id}>{tieText && <p className={styles.tieNote}>{tieText}</p>}{descriptorEquivalenceGroups(group.map(c => c.scenario)).map(equivalent => <p className={styles.equivalenceNote} key={equivalent[0].id} data-testid="descriptor-equivalence">{equivalenceExplanation(equivalent)}</p>)}{group.length > 4 ? <details className={styles.disclosure}><summary>Read all {group.length} equally supported entries: {group.map(c => c.scenario.name).join(", ")}</summary>{entries}</details> : entries}</div>
  })}</div>
}
export function PreferencePlayer() {
  const [state, dispatch] = useReducer(preferenceReducer, initialPreferenceState)
  const [resetOpen, setResetOpen] = useState(false)
  const heading = useRef<HTMLHeadingElement>(null), resetTrigger = useRef<HTMLButtonElement>(null), dialog = useRef<HTMLDialogElement>(null), keepAnswers = useRef<HTMLButtonElement>(null)
  const firstRender = useRef(true)
  useEffect(() => { if (firstRender.current) { firstRender.current = false; return } heading.current?.focus(); heading.current?.scrollIntoView({ block: "start" }) }, [state.step, state.question])
  useEffect(() => { if (resetOpen) { dialog.current?.showModal(); keepAnswers.current?.focus() } else if (dialog.current?.open) { dialog.current.close(); resetTrigger.current?.focus() } }, [resetOpen])
  const question = preferenceQuestions[state.question], answer = state.answers[question.id]
  const submitted = state.submitted, result = submitted ? matchFutures(submitted) : null
  const interpretation = submitted && result ? interpretPreferences(submitted, result) : null
  const answered = preferenceQuestions.filter(q => state.answers[q.id]).length
  const shortlistIds = new Set(result?.shortlist.map(c => c.scenario.id))
  const title = state.step === "intro" ? "What conditions would you want?" : state.step === "questions" ? question.prompt : state.step === "review" ? "Review your preferred conditions" : state.step === "expectations" ? "What seems plausible to you?" : interpretation?.title ?? "Futures to consider"
  return <div>
    <nav className={styles.localNav} aria-label="Futures navigation"><Link href={futuresRoutes.collection} prefetch={false}>All futures</Link>{state.step !== "intro" && <button type="button" onClick={() => dispatch({ type: "review" })}>Review answers ({answered}/{preferenceQuestions.length})</button>}<button type="button" ref={resetTrigger} onClick={() => setResetOpen(true)} disabled={!answered && !Object.keys(state.expectations).length}>Reset this exercise</button></nav>
    <header className={styles.playerHeader}>{state.step === "questions" && <p className={styles.origin}>Preferred conditions · Question {state.question + 1} of {preferenceQuestions.length}</p>}<h1 ref={heading} tabIndex={-1}>{title}</h1></header>
    <p role="status" className={styles.notice}>{state.notice}</p>
    {state.step === "intro" && <div className={styles.reading}><p className={styles.lead}>Consider the terms of life across the whole catalogue. Your answers will point to several futures to examine, with their conflicts and open questions.</p><p>In twelve questions, judge conditions you would want or reject. Treat each hypothetical as given; technical feasibility and what you expect to happen come later. Some questions concern your participation, others the freedom of other people or common rules.</p><p>You may be uncertain, state no preference, or reject both supplied positions. If a condition is indispensable, confirm that separately. Selection never moves you on automatically; you will review before any comparison is made.</p><div className={styles.actions}><button type="button" className="cta-primary" onClick={() => dispatch({ type: "question", index: state.question })}>{answered ? "Continue your answers" : "Begin the twelve questions"}</button><Link href={futuresRoutes.collection} prefetch={false}>Browse the catalogue first</Link></div><p className={styles.small}>Responses stay in this page’s memory. Refreshing or leaving clears this session; nothing is saved to Profile or included in a share link. The Departure exercise is optional and supplies no answers here.</p></div>}
    {state.step === "questions" && <div className={styles.questionBody}><fieldset className={styles.options}><legend className={styles.srOnly}>{question.prompt}</legend>{([{ value: "present", label: question.present }, { value: "absent", label: question.absent }, ...nonPreferenceOptions] as const).map(option => <label className={styles.option} key={option.value}><input type="radio" name={question.id} value={option.value} checked={answer?.choice === option.value} onChange={() => dispatch({ type: "answer", id: question.id, choice: option.value })} /><span>{option.label}</span></label>)}</fieldset>
      {hasDirection(answer) && <div className={styles.constraint}><label><input type="checkbox" checked={answer.nonNegotiable} onChange={event => dispatch({ type: "constraint", id: question.id, confirmed: event.target.checked })} /><span>{requirementLabels[question.id][answer.choice]}</span></label><p className={styles.small}>A scenario with a clear opposite condition will be excluded from the shortlist. An unspecified condition will remain unconfirmed, not treated as meeting this requirement.</p></div>}
      <details className={styles.disclosure}><summary>Scope of this question</summary><p>{question.scope}</p></details><div className={styles.actions}><button type="button" className="cta-secondary" onClick={() => dispatch(state.question === 0 ? { type: "intro" } : { type: "question", index: state.question - 1 })}>Back</button><button type="button" className="cta-primary" disabled={!answer} onClick={() => dispatch(state.question === preferenceQuestions.length - 1 ? { type: "review" } : { type: "question", index: state.question + 1 })}>{state.question === preferenceQuestions.length - 1 ? "Review all answers" : "Next question"}</button></div></div>}
    {state.step === "review" && <><p>These are the conditions you stated. A non-negotiable is counted only where you explicitly confirmed it.</p><ol className={styles.review}>{preferenceQuestions.map((q, index) => <li key={q.id}><div><h2>{featureDefinitions[q.id].label}</h2><p>{preferenceLabel(q.id, state.answers[q.id])}</p>{state.answers[q.id]?.nonNegotiable && <strong className={styles.constraintLabel}>Confirmed non-negotiable</strong>}</div><button type="button" onClick={() => dispatch({ type: "question", index })} aria-label={`Edit question ${index + 1}: ${featureDefinitions[q.id].label}`}>{state.answers[q.id] ? "Edit" : "Answer"}</button></li>)}</ol>{!preferencesComplete(state.answers) && <p role="status">Answer every question before submitting. Uncertainty, no preference and neither position are all complete answers.</p>}<div className={styles.actions}><button type="button" className="cta-secondary" onClick={() => dispatch({ type: "question", index: state.question })}>Return to questions</button><button type="button" className="cta-primary" disabled={!preferencesComplete(state.answers)} onClick={() => dispatch({ type: "submit" })}>Compare my preferred conditions</button></div></>}
    {state.step === "result" && result && submitted && <>
      <div className={styles.resultOpening} data-testid="futures-interpretation">{interpretation?.paragraphs.map((paragraph, index) => <p key={paragraph} className={index === 0 ? styles.lead : undefined}>{paragraph}</p>)}</div>
      {result.shortlist.length > 0 && <>

        {result.shortlist.some(c => c.unconfirmedConstraints.length) && <p className={styles.requirementNote} data-testid="unconfirmed-requirements"><strong>Some indispensable conditions remain unconfirmed.</strong> {result.shortlist.filter(c => c.unconfirmedConstraints.length).map(c => `${c.scenario.name}: ${joinConditions(c.unconfirmedConstraints.map(id => desiredCondition(id, submitted)))}.`).join(" ")} These are provisional possibilities, not entries confirmed to meet every requirement.</p>}
        <Shortlist comparisons={result.shortlist} answers={submitted} />
      </>}
      {result.comparisons.some(c => c.hardConflicts.length) && <details className={styles.disclosure} data-testid="requirement-conflicts"><summary>Confirmed requirements exclude {result.comparisons.filter(c => c.hardConflicts.length).length} entries</summary><ul>{result.comparisons.filter(c => c.hardConflicts.length).map(c => <li key={c.scenario.id}><strong>{c.scenario.name}:</strong> conflicts with {joinConditions(c.hardConflicts.map(id => desiredCondition(id, submitted)))}.</li>)}</ul></details>}
      <div className={styles.actions}><button type="button" className="cta-primary" onClick={() => dispatch({ type: "expectations" })}>{state.expectationsSubmitted ? "Edit separate expectations" : "Optional: consider what seems plausible"}</button><button type="button" className="cta-secondary" onClick={() => dispatch({ type: "review" })}>Edit preferred conditions</button></div>
      {state.expectationsSubmitted && <section className={styles.section} data-testid="expectations-readback"><h2>Your expectations, separately</h2><p>{expectationFrame.horizon}. {expectationFrame.assumptions}</p><p>An attractive future can seem unlikely; an unwelcome future can seem plausible. Neither is automatically a contradiction. These assessments have not changed your preference shortlist.</p><ul className={styles.expectationReadback}>{futureCatalogue.map(s => <li key={s.id}><strong>{s.name}</strong><span>{state.expectations[s.id] ? expectationLabels[state.expectations[s.id]!] : "Unassessed"}{shortlistIds.has(s.id) ? " · On your preference shortlist" : ""}</span></li>)}</ul></section>}
      <details className={styles.disclosure}><summary>Your explicit priorities and confirmed non-negotiables</summary><dl className={styles.facts}>{preferenceQuestions.map(q => <div key={q.id}><dt>{featureDefinitions[q.id].label}</dt><dd>{preferenceLabel(q.id, submitted[q.id])}{submitted[q.id]?.nonNegotiable && <strong className={styles.constraintLabel}> · Confirmed non-negotiable</strong>}</dd></div>)}</dl></details>
      <details className={styles.disclosure}><summary>How this editorial comparison works</summary><p>{matchingMethod}</p><p className={styles.small}>{result.questionVersion} · {result.version} · {result.catalogueVersion}. Internal ordering values are not percentages, identity scores or validated measures.</p></details>
      <details className={styles.disclosure}><summary>Inspect all {futureCatalogue.length} entries against your conditions</summary>{result.comparisons.map(comparison => <article className={styles.resultEntry} key={comparison.scenario.id}><h3>{comparison.scenario.name}</h3><p className={styles.origin}>{comparison.hardConflicts.length ? "Excluded: confirmed non-negotiable conflict" : !comparison.detailSufficient ? "Too few relevant conditions are specified" : !comparison.agreementSufficient ? "Known conditions do not agree sufficiently with your preferences" : shortlistIds.has(comparison.scenario.id) ? "On the shortlist" : "Available alternative; less net support under these rules"}</p><Reasons comparison={comparison} answers={submitted} />{!comparison.supported.length && !comparison.conflicts.length && !comparison.unresolved.length && !comparison.inapplicable.length && <p>No directional conditions were supplied for comparison.</p>}</article>)}</details>
      <section className={styles.section}><h2>Compare any two worlds</h2><p>Explore their actual institutions and missing conditions. Changing this comparison does not change your answers.</p><ComparisonExplorer preserveSession /></section>
      <section className={styles.section}><h2>From desired outcomes to governing choices</h2><p>Futures asks what conditions you would want. AI Governance asks about governing priorities today. Your wishes do not determine a category there, and a previous category does not determine your wishes here.</p><p>{submitted.humanAuthority?.choice === "present" ? "If humans should retain authority, which institutions could make that authority practical rather than ceremonial?" : submitted.capabilityLimits?.choice === "present" ? "If you want capability limits, who should set and revise them?" : "Which present institutions could keep your preferred conditions open to revision?"}</p><Link href="/ai" prefetch={false}>Explore AI Governance</Link><p className={styles.small}>No earlier result or saved draft was loaded. Your Futures responses are not transferred.</p></section>
    </>}
    {state.step === "expectations" && <><p className={styles.lead}>{expectationFrame.horizon}</p><p>{expectationFrame.assumptions}</p><p>Assess any of the {futureCatalogue.length} entries. Leaving one unassessed says nothing about whether it is possible. An attractive future can seem unlikely; an unwelcome one can seem plausible.</p><div className={styles.expectations}>{futureCatalogue.map(s => <label key={s.id}><span><strong>{s.name}</strong><span className={styles.small}>{s.premise}</span></span><select aria-label={`Expectation: ${s.name}`} value={state.expectations[s.id] ?? "unassessed"} onChange={event => dispatch({ type: "expectation", id: s.id, value: event.target.value as Expectation | "unassessed" })}><option value="unassessed">Unassessed</option>{Object.entries(expectationLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>)}</div><div className={styles.actions}><button type="button" className="cta-primary" onClick={() => dispatch({ type: "read-expectations" })}>Read preferences and expectations together</button></div><p className={styles.small}>No probabilities are calculated. These judgments are separate from the preference comparison.</p></>}
    <dialog ref={dialog} className={styles.resetDialog} aria-labelledby="futures-reset-title" onCancel={() => setResetOpen(false)}><h2 id="futures-reset-title">Clear this Futures exercise?</h2><p>This clears all general preferences and expectations from this page’s memory.</p><div className={styles.actions}><button type="button" className="cta-secondary" ref={keepAnswers} onClick={() => setResetOpen(false)}>Keep my answers</button><button type="button" className="cta-primary" onClick={() => { dispatch({ type: "reset" }); setResetOpen(false) }}>Clear and start again</button></div></dialog>
  </div>
}
