import type {
  DimensionEstimate,
  ReferenceCatalog,
  ReferenceSource,
  ReferenceVersionRecord,
} from "@/lib/reference-profiles/types"
import { assertValidReferenceCatalog } from "@/lib/reference-profiles/validation"

export const REFERENCE_PROFILE_SCHEMA_VERSION = 1
export const REFERENCE_PROFILE_CATALOG_VERSION = 2

const REFERENCE_RESEARCH_DATE = "2026-07-12"
const REFERENCE_REVIEW_DATE = "2026-07-13"

const sources: ReferenceSource[] = [
  {
    id: "S1",
    title: "The False Promise of International Institutions",
    author: "John J. Mearsheimer",
    publisher: "International Security; author-hosted PDF",
    publishedAt: "1994-01-01",
    url: "https://www.mearsheimer.com/wp-content/uploads/2019/07/A0021.pdf",
    kind: "canonical-work",
    tier: 3,
  },
  {
    id: "S2",
    title: "Bound to Fail: The Rise and Fall of the Liberal International Order",
    author: "John J. Mearsheimer",
    publisher: "International Security; Belfer Center summary",
    publishedAt: "2019-01-01",
    url: "https://www.belfercenter.org/publication/bound-fail-rise-and-fall-liberal-international-order",
    kind: "canonical-work",
    tier: 3,
  },
  {
    id: "S3",
    title: "The Case for Offshore Balancing",
    author: "John J. Mearsheimer and Stephen M. Walt",
    publisher: "Foreign Affairs; author-hosted PDF",
    publishedAt: "2016-07-01",
    url: "https://www.mearsheimer.com/wp-content/uploads/2019/04/Offshore-Balancing.pdf",
    kind: "canonical-work",
    tier: 3,
  },
  {
    id: "S4",
    title: "Liberalism and Nationalism in Contemporary America",
    author: "John J. Mearsheimer",
    publisher: "PS: Political Science & Politics; author-hosted PDF",
    publishedAt: "2021-01-01",
    url: "https://www.mearsheimer.com/wp-content/uploads/2022/05/Madison-Lecture-PDF.pdf",
    kind: "canonical-work",
    tier: 3,
  },
  {
    id: "S5",
    title: "After Hegemony: Cooperation and Discord in the World Political Economy",
    author: "Robert O. Keohane",
    publisher: "Princeton University Press; JSTOR",
    publishedAt: "1984-01-01",
    url: "https://www.jstor.org/stable/j.ctt7sq9s",
    kind: "canonical-work",
    tier: 3,
  },
  {
    id: "S6",
    title: "International Institutions: Two Approaches",
    author: "Robert O. Keohane",
    publisher: "International Studies Quarterly; archive PDF",
    publishedAt: "1988-01-01",
    url: "https://www.rochelleterman.com/ir/sites/default/files/keohane1988.pdf",
    kind: "canonical-work",
    tier: 3,
  },
  {
    id: "S7",
    title: "International Institutions: Can Interdependence Work?",
    author: "Robert O. Keohane",
    publisher: "Foreign Policy; archive PDF",
    publishedAt: "1998-01-01",
    url: "https://www.columbia.edu/itc/sipa/S6800/courseworks/international_keohane.pdf",
    kind: "canonical-work",
    tier: 3,
  },
  {
    id: "S8",
    title: "Governance in a Partially Globalized World",
    author: "Robert O. Keohane",
    publisher: "American Political Science Review; archive PDF",
    publishedAt: "2001-03-01",
    url: "https://www.guillaumenicaise.com/wp-content/uploads/2013/10/Keohane_Governance-in-a-Partially-Globalized-World.pdf",
    kind: "canonical-work",
    tier: 3,
  },
  {
    id: "S9",
    title: "Anarchy is What States Make of It: The Social Construction of Power Politics",
    author: "Alexander Wendt",
    publisher: "International Organization; archive PDF",
    publishedAt: "1992-01-01",
    url: "https://www.rochelleterman.com/ir/sites/default/files/Wendt%201992.pdf",
    kind: "canonical-work",
    tier: 3,
  },
  {
    id: "S10",
    title: "Social Theory of International Politics",
    author: "Alexander Wendt",
    publisher: "Cambridge University Press; archive PDF",
    publishedAt: "1999-01-01",
    url: "https://www.guillaumenicaise.com/wp-content/uploads/2013/10/Wendt-Social-Theory-of-International-Politics.pdf",
    kind: "canonical-work",
    tier: 3,
  },
  {
    id: "S11",
    title: "Collective Identity Formation and the International State",
    author: "Alexander Wendt",
    publisher: "American Political Science Review; Cambridge Core",
    publishedAt: "1994-06-01",
    url: "https://www.cambridge.org/core/journals/american-political-science-review/article/collective-identity-formation-and-the-international-state/154116B3857B8A791143C13987F922C0",
    kind: "canonical-work",
    tier: 3,
  },
  {
    id: "S12",
    title: "States and Markets",
    author: "Susan Strange",
    publisher: "Basil Blackwell; Bloomsbury Academic edition page",
    publishedAt: "1988-01-01",
    url: "https://www.bloomsbury.com/us/states-and-markets-9781474236935/",
    kind: "canonical-work",
    tier: 3,
  },
  {
    id: "S13",
    title: "The Retreat of the State: The Diffusion of Power in the World Economy",
    author: "Susan Strange",
    publisher: "Cambridge University Press; preview PDF",
    publishedAt: "1996-01-01",
    url: "https://api.pageplace.de/preview/DT0400.9780511837340_A23680086/preview-9780511837340_A23680086.pdf",
    kind: "canonical-work",
    tier: 3,
  },
  {
    id: "S14",
    title: "Mad Money",
    author: "Susan Strange",
    publisher: "University of Warwick; working paper PDF",
    publishedAt: "1998-01-01",
    url: "https://wrap.warwick.ac.uk/id/eprint/2107/1/WRAP_Strange_wp1898.pdf",
    kind: "canonical-work",
    tier: 3,
  },
]

function estimate(
  value: number,
  support: DimensionEstimate["support"],
  sourceIds: string[],
  evidenceIds: string[],
  note: string,
): DimensionEstimate {
  return { value, support, sourceIds, evidenceIds, note }
}

function publishedVersionHistory(changeNote: string): ReferenceVersionRecord[] {
  return [
    { version: 1, changedAt: REFERENCE_RESEARCH_DATE, changeNote },
    {
      version: 2,
      changedAt: REFERENCE_REVIEW_DATE,
      changeNote: "Published after second-person evidence review against the approved source pack.",
    },
  ]
}

const publishedReviewRecord = {
  public: true,
  publicationStatus: "published" as const,
  reviewedAt: REFERENCE_REVIEW_DATE,
  reviewers: [
    {
      reviewerId: "v16-initial-coder",
      role: "coder" as const,
      reviewedAt: REFERENCE_RESEARCH_DATE,
    },
    {
      reviewerId: "v16-approved-source-pack-second-reader",
      role: "second-reader" as const,
      reviewedAt: REFERENCE_REVIEW_DATE,
    },
  ],
  version: 2,
}

export const REFERENCE_PROFILE_CATALOG: ReferenceCatalog = {
  schemaVersion: REFERENCE_PROFILE_SCHEMA_VERSION,
  catalogVersion: REFERENCE_PROFILE_CATALOG_VERSION,
  generatedAt: REFERENCE_REVIEW_DATE,
  dataStatus: "public",
  notice:
    "Published thinker profiles are evidence-coded interpretations reviewed against the listed canonical works and sources.",
  sources,
  profiles: [
    {
      ...publishedReviewRecord,
      id: "john-mearsheimer",
      name: "John Mearsheimer",
      shortName: "Mearsheimer",
      entityType: "thinker",
      scope: "foundation",
      asOf: REFERENCE_RESEARCH_DATE,
      evidenceWindow: { start: "1994-01-01", end: "2021-01-01" },
      domain: "International relations theory and U.S. grand strategy",
      scopeNote: "Canonical theory and later grand-strategy essays in the coded source record.",
      summary:
        "This profile codes an offensive-realist account of competition alongside later arguments for offshore balancing.",
      sourceIds: ["S1", "S2", "S3", "S4"],
      evidence: [
        {
          id: "mearsheimer-e1",
          scope: "ir",
          sourceId: "S1",
          dimensionKeys: ["securityCompetition", "institutions", "domesticFilters"],
          note: "Sets out the systemic competition claim and the limited independent force assigned to institutions.",
        },
        {
          id: "mearsheimer-e2",
          scope: "ir",
          sourceId: "S2",
          dimensionKeys: [
            "securityCompetition",
            "institutions",
            "normsIdentity",
            "politicalEconomy",
            "orderJustice",
          ],
          note: "Develops the critique of liberal order through power, nationalism, and prudential order.",
        },
        {
          id: "mearsheimer-e3",
          scope: "ir",
          sourceId: "S3",
          dimensionKeys: [
            "securityCompetition",
            "politicalEconomy",
            "restraint",
            "orderJustice",
          ],
          note: "Provides the later policy case for selective engagement and offshore balancing.",
        },
        {
          id: "mearsheimer-e4",
          scope: "ir",
          sourceId: "S4",
          dimensionKeys: ["domesticFilters", "normsIdentity", "orderJustice"],
          note: "Supports the coding of nationalism, domestic legitimacy, and political order.",
        },
      ],
      dimensionEstimates: {
        securityCompetition: estimate(
          7,
          "strong",
          ["S1", "S2", "S3"],
          ["mearsheimer-e1", "mearsheimer-e2", "mearsheimer-e3"],
          "Security competition is the core of his theory. Survival under anarchy pushes states to compete for power.",
        ),
        institutions: estimate(
          1,
          "strong",
          ["S1", "S2"],
          ["mearsheimer-e1", "mearsheimer-e2"],
          "Institutions are treated as weak constraints relative to power and nationalism.",
        ),
        domesticFilters: estimate(
          2,
          "partial",
          ["S1", "S4"],
          ["mearsheimer-e1", "mearsheimer-e4"],
          "Domestic politics can matter, but mainly outside the core realist baseline.",
        ),
        normsIdentity: estimate(
          3,
          "partial",
          ["S2", "S4"],
          ["mearsheimer-e2", "mearsheimer-e4"],
          "Nationalism matters in later work, but identity is not his main constitutive variable.",
        ),
        politicalEconomy: estimate(
          3,
          "partial",
          ["S2", "S3"],
          ["mearsheimer-e2", "mearsheimer-e3"],
          "He recognises the world economy, but places security competition above interdependence.",
        ),
        restraint: estimate(
          4,
          "partial",
          ["S3"],
          ["mearsheimer-e3"],
          "Theory leans advantage-seeking; later policy writing leans restraint through offshore balancing.",
        ),
        orderJustice: estimate(
          6,
          "strong",
          ["S2", "S3", "S4"],
          ["mearsheimer-e2", "mearsheimer-e3", "mearsheimer-e4"],
          "He favours stability and prudence over liberal-democratic transformation abroad.",
        ),
      },
      disputes: [
        "Offensive realism points toward power maximisation.",
        "Offshore balancing points toward selective restraint.",
      ],
      versionHistory: publishedVersionHistory("Created as a non-public research draft."),
    },
    {
      ...publishedReviewRecord,
      id: "robert-keohane",
      name: "Robert Keohane",
      shortName: "Keohane",
      entityType: "thinker",
      scope: "foundation",
      asOf: REFERENCE_RESEARCH_DATE,
      evidenceWindow: { start: "1984-01-01", end: "2001-03-01" },
      domain: "Institutions, interdependence, and global governance",
      scopeNote: "Canonical institutionalist works and later governance writing in the coded source record.",
      summary:
        "This profile codes institutions as durable channels for cooperation and gives later work added weight on legitimacy and accountability.",
      sourceIds: ["S5", "S6", "S7", "S8"],
      evidence: [
        {
          id: "keohane-e1",
          scope: "ir",
          sourceId: "S5",
          dimensionKeys: ["securityCompetition", "institutions", "politicalEconomy"],
          note: "Frames cooperation under anarchy through regimes and interdependence.",
        },
        {
          id: "keohane-e2",
          scope: "ir",
          sourceId: "S6",
          dimensionKeys: ["securityCompetition", "institutions", "normsIdentity"],
          note: "Sets the institutional research program alongside interpretive approaches.",
        },
        {
          id: "keohane-e3",
          scope: "ir",
          sourceId: "S7",
          dimensionKeys: ["institutions", "politicalEconomy", "restraint"],
          note: "Connects rules and expectations to cooperation under interdependence.",
        },
        {
          id: "keohane-e4",
          scope: "ir",
          sourceId: "S8",
          dimensionKeys: ["domesticFilters", "normsIdentity", "restraint", "orderJustice"],
          note: "Adds participation, persuasion, accountability, and legitimacy to the governance account.",
        },
      ],
      dimensionEstimates: {
        securityCompetition: estimate(
          3,
          "partial",
          ["S5", "S6"],
          ["keohane-e1", "keohane-e2"],
          "He takes anarchy and power seriously but not as the whole story.",
        ),
        institutions: estimate(
          7,
          "strong",
          ["S5", "S6", "S7"],
          ["keohane-e1", "keohane-e2", "keohane-e3"],
          "Institutions, expectations and rules are central to cooperation.",
        ),
        domesticFilters: estimate(
          5,
          "partial",
          ["S8"],
          ["keohane-e4"],
          "Later work gives visible weight to accountability and participation.",
        ),
        normsIdentity: estimate(
          4,
          "partial",
          ["S6", "S8"],
          ["keohane-e2", "keohane-e4"],
          "Legitimacy and beliefs matter, though not in a full constructivist way.",
        ),
        politicalEconomy: estimate(
          5,
          "strong",
          ["S5", "S7"],
          ["keohane-e1", "keohane-e3"],
          "World political economy and regime-managed interdependence are central terrain.",
        ),
        restraint: estimate(
          4,
          "partial",
          ["S7", "S8"],
          ["keohane-e3", "keohane-e4"],
          "He prefers negotiated cooperation but does not elevate strategic restraint as a doctrine.",
        ),
        orderJustice: estimate(
          4,
          "partial",
          ["S8"],
          ["keohane-e4"],
          "He wants effective governance with legitimacy and accountability, not mere order-preservation.",
        ),
      },
      disputes: [
        "Early work can be read as relatively thin and state-centric.",
        "Later governance work broadens the role of legitimacy and belief.",
      ],
      versionHistory: publishedVersionHistory("Created as a non-public research draft."),
    },
    {
      ...publishedReviewRecord,
      id: "alexander-wendt",
      name: "Alexander Wendt",
      shortName: "Wendt",
      entityType: "thinker",
      scope: "foundation",
      asOf: REFERENCE_RESEARCH_DATE,
      evidenceWindow: { start: "1992-01-01", end: "1999-01-01" },
      domain: "Constructivist international relations theory",
      scopeNote: "Canonical texts on identity formation and cultures of anarchy in the coded source record.",
      summary:
        "This profile codes rivalry as socially contingent and gives identity its greatest explanatory weight.",
      sourceIds: ["S9", "S10", "S11"],
      evidence: [
        {
          id: "wendt-e1",
          scope: "ir",
          sourceId: "S9",
          dimensionKeys: [
            "securityCompetition",
            "institutions",
            "normsIdentity",
            "restraint",
            "orderJustice",
          ],
          note: "Establishes the contingency of rivalry and the social formation of interests.",
        },
        {
          id: "wendt-e2",
          scope: "ir",
          sourceId: "S10",
          dimensionKeys: [
            "securityCompetition",
            "institutions",
            "domesticFilters",
            "normsIdentity",
            "restraint",
            "orderJustice",
          ],
          note: "Develops the systemic framework through distinct cultures of anarchy.",
        },
        {
          id: "wendt-e3",
          scope: "ir",
          sourceId: "S11",
          dimensionKeys: ["institutions", "normsIdentity", "orderJustice"],
          note: "Supports the coding of collective identity and possible transformations of order.",
        },
      ],
      dimensionEstimates: {
        securityCompetition: estimate(
          2,
          "partial",
          ["S9", "S10"],
          ["wendt-e1", "wendt-e2"],
          "Rivalry is contingent, not inherent in anarchy.",
        ),
        institutions: estimate(
          5,
          "partial",
          ["S9", "S10", "S11"],
          ["wendt-e1", "wendt-e2", "wendt-e3"],
          "Rules matter as part of social structure, though regime design is not the main concern.",
        ),
        domesticFilters: estimate(
          2,
          "sparse",
          ["S10"],
          ["wendt-e2"],
          "The main framework is systemic, not domestic.",
        ),
        normsIdentity: estimate(
          7,
          "strong",
          ["S9", "S10", "S11"],
          ["wendt-e1", "wendt-e2", "wendt-e3"],
          "Identities and interests are socially produced and reproduced in interaction.",
        ),
        restraint: estimate(
          4,
          "sparse",
          ["S9", "S10"],
          ["wendt-e1", "wendt-e2"],
          "The score depends on which culture of anarchy is in view.",
        ),
        orderJustice: estimate(
          3,
          "partial",
          ["S9", "S10", "S11"],
          ["wendt-e1", "wendt-e2", "wendt-e3"],
          "The work allows movement toward friendship, mutual aid and more solidaristic order forms.",
        ),
      },
      disputes: [
        "The political-economy dimension remains uncoded because the source base is too thin for reliable coding.",
        "Wendt leaves room for rivalry and enmity as well as friendship.",
        "The framework is contingent rather than normatively linear.",
      ],
      versionHistory: publishedVersionHistory(
        "Imported as a reading-card research draft with one uncoded dimension.",
      ),
    },
    {
      ...publishedReviewRecord,
      id: "susan-strange",
      name: "Susan Strange",
      shortName: "Strange",
      entityType: "thinker",
      scope: "foundation",
      asOf: REFERENCE_RESEARCH_DATE,
      evidenceWindow: { start: "1988-01-01", end: "1998-01-01" },
      domain: "International political economy and structural power",
      scopeNote: "Core works on structural power, markets, finance, and diffused authority in the coded source record.",
      summary:
        "This profile centers structural power in production, finance, knowledge, and the changing authority of states and markets.",
      sourceIds: ["S12", "S13", "S14"],
      evidence: [
        {
          id: "strange-e1",
          scope: "ir",
          sourceId: "S12",
          dimensionKeys: ["securityCompetition", "politicalEconomy"],
          note: "Frames security, production, finance, and knowledge as structures of power.",
        },
        {
          id: "strange-e2",
          scope: "ir",
          sourceId: "S13",
          dimensionKeys: [
            "institutions",
            "domesticFilters",
            "normsIdentity",
            "politicalEconomy",
            "restraint",
            "orderJustice",
          ],
          note: "Supports the coding of diffused authority, structural power, and distributive consequences.",
        },
        {
          id: "strange-e3",
          scope: "ir",
          sourceId: "S14",
          dimensionKeys: ["politicalEconomy", "orderJustice"],
          note: "Provides additional support on finance, volatility, and structural consequences.",
        },
      ],
      dimensionEstimates: {
        securityCompetition: estimate(
          4,
          "partial",
          ["S12"],
          ["strange-e1"],
          "Security is one structure of power, but not automatically the dominant one.",
        ),
        institutions: estimate(
          2,
          "partial",
          ["S13"],
          ["strange-e2"],
          "Formal rules matter less than structural power and non-state authority.",
        ),
        domesticFilters: estimate(
          4,
          "sparse",
          ["S13"],
          ["strange-e2"],
          "Domestic and international authority are entangled, though this is not her primary coding axis.",
        ),
        normsIdentity: estimate(
          3,
          "sparse",
          ["S13"],
          ["strange-e2"],
          "Not central to the framework used here.",
        ),
        politicalEconomy: estimate(
          7,
          "strong",
          ["S12", "S13", "S14"],
          ["strange-e1", "strange-e2", "strange-e3"],
          "Production, finance, knowledge and non-state structural power define her worldview.",
        ),
        restraint: estimate(
          4,
          "sparse",
          ["S13"],
          ["strange-e2"],
          "The framework is diagnostic rather than grand-strategic.",
        ),
        orderJustice: estimate(
          3,
          "partial",
          ["S13", "S14"],
          ["strange-e2", "strange-e3"],
          "Her work is sensitive to hierarchy, volatility and who benefits from the system.",
        ),
      },
      disputes: [
        "She continues to see state power, especially U.S. structural power, as real.",
        "She also argues that authority has diffused sharply toward non-state actors.",
      ],
      versionHistory: publishedVersionHistory("Created as a non-public research draft."),
    },
  ],
  movements: [],
}

assertValidReferenceCatalog(REFERENCE_PROFILE_CATALOG)

export const referenceProfileCatalog = REFERENCE_PROFILE_CATALOG

export function getReferenceProfileById(id: string) {
  return REFERENCE_PROFILE_CATALOG.profiles.find((profile) => profile.id === id)
}
