import type { Metadata } from "next"
import Link from "next/link"
import { futureCatalogue, catalogueVersion, futuresRoutes } from "@/lib/futures/catalogue/index"
import { futuresSources } from "@/lib/futures/sources"
import { CatalogueEntry } from "@/components/futures/catalogue-content"
import { TrajectoryMap } from "@/components/futures/trajectory-map"
import styles from "@/components/futures/catalogue.module.css"

export const metadata: Metadata = { title: "Futures | IR Worldview Inventory", description: "Browse possible human and AI futures, compare desired conditions, and consider expectations separately." }
export default function FuturesPage() {
  return <article className={styles.page} lang="en">
    <header className={styles.header}><h1>Which futures could you live with?</h1><p className={styles.lead}>Different forms of power. Different ways of living. Open questions about what comes next.</p><p>Browse {futureCatalogue.length} possible futures, compare any two, or consider the conditions you would want through twelve questions. You can then record what seems plausible separately.</p><div className={styles.actions}><Link href={futuresRoutes.preferences} prefetch={false} className="cta-primary">Consider your preferred conditions</Link><a href="#catalogue" className="cta-secondary">Browse all futures</a><Link href={futuresRoutes.compare} prefetch={false}>Compare two scenarios</Link></div><p className={styles.small}>English editorial draft · {futureCatalogue.length} catalogue entries · {futureCatalogue.filter(s => s.exercise).length} optional exercise. These overlap; they are not a set of exclusive destinies.</p></header>
    <section id="catalogue" className={styles.section} aria-labelledby="catalogue-title"><h2 id="catalogue-title">The catalogue</h2><p>The original twelve scenarios from Max Tegmark’s <em>Life 3.0</em> sit alongside project-authored possibilities. A feared future can belong here without being made attractive.</p><nav className={styles.index} aria-label="Every published future">{futureCatalogue.map(s => <a key={s.id} href={`#trajectory-${s.id}`}>{s.name}</a>)}</nav><div>{futureCatalogue.map(s => <CatalogueEntry key={s.id} scenario={s} />)}</div></section>
    <details className={styles.disclosure}><summary>The historical map of the twelve inherited scenarios</summary><p>The existing positions and aliases are preserved as an editorial orientation. The seven project-authored additions are described in the catalogue rather than assigned invented coordinates. The list above is the complete collection; map positions never enter preference matching.</p><TrajectoryMap /></details>
    <section id="source-and-scope" className={styles.sources}><h2>Source and scope</h2><p>The twelve inherited concepts are credited to Max Tegmark’s <a href={futuresSources.book.url}>Life 3.0</a>, chapter 5. <a href={futuresSources.aftermath.url}>FLI’s scenario reference</a> anchors short original-premise paraphrases. Original names and prior project aliases remain visible. Attribution does not imply permission or endorsement.</p><p>New scenarios, life-and-institution accounts, comparisons and feature descriptors are project-authored hypothetical or editorial material. Each entry identifies what is unspecified. Earlier unsupported current-development and community-attribution claims remain withheld; no current scientific headline is used to establish a future or its likelihood.</p><p className={styles.small}>{catalogueVersion} · Sources checked 11 September 2026. Catalogue matching is separate from Foundation and AI Governance scoring. General choices and expectations stay in page memory; The Departure is optional and contributes no answers to either.</p></section>
  </article>
}
